name: My CICD Pipeline in GitHub Actions

on:
 push:
  branches: main
  
jobs:
  build:
    runs-on: ubuntu-latest

  steps:
   - users: actions/checkout@v4
   - name: My first steps:
     run: |
      echo "This is DevOps Tutorials"
      uname -a
   

