name: My CICD Pipeline in GitHub Actions

on:
 push:
  branches: main
  
jobs:
  build:
    runs-on: ubuntu-24.04

  steps:
   - users: actions/checkout@v4
   
   - name: Initialize Repo
    run: |
      echo "This is DevOps Tutorials"
      uname -a

   - name : Check the docker installation
    run: |
       docker
       docker images
       
   - name : Run Docker Container
    run: |
        docker run hello-world
   

